# Meta Data for SEO

## Homepage
title = "Sprinto"
titleSeparator = "-"
titleAddition = "Discord sprinting bot"
description = "Sprinto brings creators together."

## Documentation
# docsVersion = "0.3"

## Open Graph
# images = ["doks.png"]
ogLocale = "en_US"
# domainTLD = "doks.netlify.app"
domainTLD = "sprintobot.com"
titleHome = "Sprinto bot"

## Twitter Cards
twitterSite = "@sprintobot"
twitterCreator = "@pengowray"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Sprinto Discord Bot"
schemaAuthor = "Pengo Wray"
schemaAuthorTwitter = "https://twitter.com/pengowray"
# schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/pengowray"
schemaLocale = "en-US"
# TODO
# schemaLogo = "logo-doks.png"
# schemaLogoWidth = 512
# schemaLogoHeight = 512
# schemaImage = "doks.png"
# schemaImageWidth = 1280
# schemaImageHeight = 640
schemaTwitter = "https://twitter.com/sprintobot"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/pengowray/sprinto"
schemaSection = "blog"

googleAnalytics = 'G-KJELGBPRHT'

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
#footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"
#footer = "Powered by <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a> and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"
#footer = "[Invite Sprinto](https://discord.com/oauth2/authorize?client_id=421646775749967872&scope=bot&permissions=2419424576) ⸻ [Join Support Server](https://discord.gg/7ZSuEgM) ⸻ [top.gg](https://top.gg/bot/421646775749967872) ⸻ [Sprinto on Patreon](https://www.patreon.com/pengowray)** ⸻ [Buy me a coffee](https://ko-fi.com/pengowray) (Ko-fi)"
#footer = "<a href=\"https://discord.gg/7ZSuEgM\">Sprinto Support Server</a> ⸻ <a href=\"https://www.patreon.com/pengowray\">Sprinto on Patreon</a> ⸻ <a href=\"https://ko-fi.com/pengowray\">Buy me a coffee</a> (Ko-fi) <br> Powered by <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a> and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"
footer = """<a class=\"text-muted\" href=\"https://discord.gg/7ZSuEgM\">Join Sprinto's Support Server</a>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-KJELGBPRHT"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-KJELGBPRHT');
</script>
"""

# Feed
copyRight = "Copyright (c) 2023 Pengo Wray"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
# alertText = "Introducing Sprinto! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"
alertText = "Introducing Sprinto!"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/pengowray/doks-sprinto"
docsRepoBranch = "master"
# docsRepoSubPath = ""
docsRepoSubPath = "docs"
editPage = false
lastMod = false

[sections]
  # sectionNav = ["docs", "guides"]
  sectionNav = ["docs", "blog"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = false
